language: generic
branches:
  only:
  - master
jobs:
  include:
  - stage: Package
    name: Create v2ray package for crew
    script:
    # - sudo apt update
    # - sudo apt install tree grep jq -y
    - go get github.com/ericchiang/pup
    - sh -f ./v2.v2ray_package_crew.sh

